import { Inconsolata } from "next/font/google";
import Navbar from "./_components/Navbar";
import "./globals.css";

const font = Inconsolata({ subsets: ["latin"] });

export const metadata = {
  title: "Mohamed Shadhaan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${font.className} bg-stone-100 dark:bg-stone-900 dark:text-stone-300 flex flex-col justify-center mx-auto w-full max-w-5xl`}
      >
        <header className="mt-40 pb-20">
          <Navbar />
        </header>
        <main className="w-full">{children}</main>
      </body>
    </html>
  );
}
